[versions]
agp = "8.9.1"
kotlin = "2.1.0"
espresso-core = "3.5.1"
sincmaths = "0.3"
dokka = "1.9.10"

[libraries]
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
sincmaths = { module = "io.github.gallvp:sincmathsmp", version.ref = "sincmaths" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
